osx_image: xcode8
language: objective-c


script:
   - set -o pipefail
   - xcodebuild clean test -project later.xcodeproj -scheme later -destination "platform=iOS Simulator,name=iPhone 6 Plus" | xcpretty