osx_image: xcode8.2
language: objective-c


script:
   - set -o pipefail
   - xcodebuild clean test -project later.xcodeproj -scheme later -destination "id=8188B40E-F57F-4519-AC47-E43D884B9016" | xcpretty